In [1]:
import pandas as pd
import numpy as np
import datetime 
import matplotlib.pyplot as plt

feature_data = pd.read_pickle("feature_data_ready.pkl")
response = pd.read_pickle("Step2_Y_variable.pkl")
feature_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3523 entries, 1996-12-31 to 2016-12-23
Columns: 132 entries, PET.RCLC3.D to dollar_index
dtypes: float64(132)
memory usage: 3.6 MB

In [2]:
response_data = response['19961231':'20161223']
response_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5031 entries, 1996-12-31 to 2016-12-23
Data columns (total 26 columns):
Price                          5031 non-null float64
Daily_Return                   5031 non-null float64
Pre1MonthAvgDailyRet           5031 non-null object
Pre2MonthAvgDailyRet           5031 non-null object
Pre3MonthAvgDailyRet           5031 non-null object
Pre6MonthAvgDailyRet           5031 non-null object
Pre1MonthVolDaily              5031 non-null object
Pre2MonthVolDaily              5031 non-null object
Pre3MonthVolDaily              5031 non-null object
Pre6MonthVolDaily              5031 non-null object
Pre1MonthDailyPriceRange       5031 non-null object
Pre2MonthDailyPriceRange       5031 non-null object
Pre3MonthDailyPriceRange       5031 non-null object
Pre6MonthDailyPriceRange       5031 non-null object
next1MonthAvgDailyRet          5031 non-null object
next2MonthAvgDailyRet          5031 non-null object
next3MonthAvgDailyRet          5031 non-null object
next6MonthAvgDailyRet          5031 non-null object
next1MonthVolDaily             5031 non-null object
next2MonthVolDaily             5031 non-null object
next3MonthVolDaily             5031 non-null object
next6MonthVolDaily             5031 non-null object
next1MonthAvgDailyRet_Label    5031 non-null float64
next2MonthAvgDailyRet_Label    5031 non-null float64
next3MonthAvgDailyRet_Label    5031 non-null float64
next6MonthAvgDailyRet_Label    5031 non-null float64
dtypes: float64(6), object(20)
memory usage: 1.0+ MB

In [3]:
refer_time = feature_data.index
response_data = response_data.loc[refer_time,:]
response_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 3523 entries, 1996-12-31 to 2016-12-23
Data columns (total 26 columns):
Price                          3523 non-null float64
Daily_Return                   3523 non-null float64
Pre1MonthAvgDailyRet           3523 non-null object
Pre2MonthAvgDailyRet           3523 non-null object
Pre3MonthAvgDailyRet           3523 non-null object
Pre6MonthAvgDailyRet           3523 non-null object
Pre1MonthVolDaily              3523 non-null object
Pre2MonthVolDaily              3523 non-null object
Pre3MonthVolDaily              3523 non-null object
Pre6MonthVolDaily              3523 non-null object
Pre1MonthDailyPriceRange       3523 non-null object
Pre2MonthDailyPriceRange       3523 non-null object
Pre3MonthDailyPriceRange       3523 non-null object
Pre6MonthDailyPriceRange       3523 non-null object
next1MonthAvgDailyRet          3523 non-null object
next2MonthAvgDailyRet          3523 non-null object
next3MonthAvgDailyRet          3523 non-null object
next6MonthAvgDailyRet          3523 non-null object
next1MonthVolDaily             3523 non-null object
next2MonthVolDaily             3523 non-null object
next3MonthVolDaily             3523 non-null object
next6MonthVolDaily             3523 non-null object
next1MonthAvgDailyRet_Label    3523 non-null float64
next2MonthAvgDailyRet_Label    3523 non-null float64
next3MonthAvgDailyRet_Label    3523 non-null float64
next6MonthAvgDailyRet_Label    3523 non-null float64
dtypes: float64(6), object(20)
memory usage: 743.1+ KB

In [4]:
response_data.apply(lambda x: sum(x.isna()),axis=0)

Price                          0
Daily_Return                   0
Pre1MonthAvgDailyRet           0
Pre2MonthAvgDailyRet           0
Pre3MonthAvgDailyRet           0
Pre6MonthAvgDailyRet           0
Pre1MonthVolDaily              0
Pre2MonthVolDaily              0
Pre3MonthVolDaily              0
Pre6MonthVolDaily              0
Pre1MonthDailyPriceRange       0
Pre2MonthDailyPriceRange       0
Pre3MonthDailyPriceRange       0
Pre6MonthDailyPriceRange       0
next1MonthAvgDailyRet          0
next2MonthAvgDailyRet          0
next3MonthAvgDailyRet          0
next6MonthAvgDailyRet          0
next1MonthVolDaily             0
next2MonthVolDaily             0
next3MonthVolDaily             0
next6MonthVolDaily             0
next1MonthAvgDailyRet_Label    0
next2MonthAvgDailyRet_Label    0
next3MonthAvgDailyRet_Label    0
next6MonthAvgDailyRet_Label    0
dtype: int64

In [5]:
response_data.head()

,Price,Daily_Return,Pre1MonthAvgDailyRet,Pre2MonthAvgDailyRet,Pre3MonthAvgDailyRet,Pre6MonthAvgDailyRet,Pre1MonthVolDaily,Pre2MonthVolDaily,Pre3MonthVolDaily,Pre6MonthVolDaily,...,next3MonthAvgDailyRet,next6MonthAvgDailyRet,next1MonthVolDaily,next2MonthVolDaily,next3MonthVolDaily,next6MonthVolDaily,next1MonthAvgDailyRet_Label,next2MonthAvgDailyRet_Label,next3MonthAvgDailyRet_Label,next6MonthAvgDailyRet_Label
Date,,,,,,,,,,,,,,,,,,,,,
1996-12-31,25.90,0.021696,0.00368008,0.00130641,0.0010388,0.00172152,0.0248342,0.027265,0.0244861,0.0220687,...,-0.00374377,-0.00196119,0.0170061,0.0169067,0.018873,0.0188191,5.0,6.0,6.0,6.0
1997-01-02,25.55,-0.013514,0.004538,0.00332857,0.00150423,0.00178124,0.0245375,0.0265703,0.0247508,0.0221125,...,-0.00413747,-0.00161174,0.0172481,0.0172916,0.0191414,0.0188243,5.0,6.0,6.0,6.0
1997-01-03,25.55,0.000000,0.00188525,0.00291779,0.000749758,0.0015721,0.0233033,0.0263725,0.0244826,0.0221326,...,-0.0043823,-0.00196595,0.0172682,0.0173097,0.0191855,0.0192067,5.0,6.0,6.0,6.0
1997-01-06,26.25,0.027397,0.00018301,0.0033726,0.000814664,0.00169035,0.0238642,0.0265947,0.0244752,0.0220843,...,-0.00473429,-0.00220085,0.0165381,0.0172954,0.0187988,0.0191022,5.0,6.0,6.0,6.0
1997-01-07,26.25,0.000000,0.00162497,0.00394716,0.000930716,0.00183826,0.0246252,0.026858,0.0245837,0.0221938,...,-0.00465183,-0.00218032,0.0173775,0.0174851,0.0188307,0.0191059,5.0,6.0,6.0,6.0

In [6]:
feature_data = feature_data.join(response_data.iloc[:,list(range(2,10))])
sum(feature_data.apply(lambda x: sum(x.isna())))

0

In [7]:
response_data.to_pickle("response_data.pkl")
feature_data.to_pickle("feature_data_final_ready.pkl")